# Generated by Django 6.1.1 on 2026-09-11 01:32

import django.db.models.deletion
import invites.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=invites.models.generate_code, editable=False, max_length=32, unique=True)),
                ('label', models.CharField(help_text="Who or where this is for, e.g. 'Volunteer room QR' or 'Jane Smith'.", max_length=120)),
                ('max_uses', models.PositiveIntegerField(blank=True, default=1, help_text='How many accounts can be created with this invite. Leave blank for unlimited.', null=True)),
                ('use_count', models.PositiveIntegerField(default=0, editable=False)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. After this time the invite stops working.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to shut this invite off immediately.')),
                ('requires_approval', models.BooleanField(default=False, help_text='New accounts from this invite stay disabled until staff approve them. Recommended for posted QR codes.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InviteRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='invites.invitecode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite_redemption', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
